
version: '3.8'

services:
  openproject:
    image: openproject/community:latest
    container_name: openproject
    ports:
      - "8080:80"
    restart: always

  devlake:
    image: apache/devlake:latest
    container_name: devlake
    ports:
      - "8081:4000"
    restart: always